Check destination exists

diff --git a/bin/create-link b/bin/create-link
--- a/bin/create-link
+++ b/bin/create-link
@@ -4,12 +4,16 @@ FROM=$1
 TO=$2
 
 >&2 echo "----> Creating a symlink from ${FROM} to ${TO}..."
-if [[ -L $FROM ]]; then
+if [[ -L "$FROM" ]]; then
   >&2 echo "----> Symlink '${FROM}' already exists..."
   exit 0
 fi
+if [[ ! -e "$TO" ]]; then
+  >&2 echo "ERROR: Destination '${TO}' does not exists."
+  exit 3
+fi
 
-ln -sf $TO $FROM
+ln -sf "$TO" "$FROM"
 
 >&2 echo "----> Done linking '${FROM}'."
 exit 0
