Output errors

diff --git a/bin/install_application b/bin/install_application
--- a/bin/install_application
+++ b/bin/install_application
@@ -6,6 +6,10 @@ APPLICATION_NAME=$1
 brew cask list | grep $APPLICATION_NAME >/dev/null
 if [[ $? -ne 0 ]]; then
   brew cask install $APPLICATION_NAME
+  if [[ $? -ne 0 ]]; then
+    >&2 echo "----> ERROR: trying to install '${APPLICATION_NAME}'..."
+    exit 3
+  fi
 fi
 
 >&2 echo "----> Done installing '${APPLICATION_NAME}'."
diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -9,41 +9,42 @@ sudo -v
 if [[ ! -d /Library/Developer/CommandLineTools ]]; then
   >&2 echo "----> Installing Xcode command line tools..."
   xcode-select --install
-  >&2 echo "----> Re-run setup after Xcode command line tools has been installed."
+  >&2 echo "----> NOTE: Re-run setup after Xcode command line tools has been installed."
   exit 3
 fi
 
 >&2 echo "----> Installing Homebrew..."
 curl https://raw.githubusercontent.com/Homebrew/install/master/install >/tmp/install_homebrew.rb
 if [[ $? -ne 0 ]]; then
-  >&2 echo "----> Failed to download homebrew installer."
+  >&2 echo "----> ERROR: Failed to download homebrew installer."
   exit 4
 fi
 echo | ruby /tmp/install_homebrew.rb
 
 >&2 echo "----> Installing command-line programs with Homebrew..."
-brew install ag 2>/dev/null
-brew install binutils 2>/dev/null
-brew install cloc 2>/dev/null
-brew install coreutils 2>/dev/null
-brew install exiftool 2>/dev/null
-brew install ffmpeg 2>/dev/null
-brew install git 2>/dev/null
-brew install git-lfs 2>/dev/null
-brew install git-when-merged 2>/dev/null
-brew install haskell-stack 2>/dev/null
-brew install jq 2>/dev/null
-brew install node 2>/dev/null
-brew install osquery 2>/dev/null
-brew install p7zip 2>/dev/null
-brew install parallel 2>/dev/null
-brew install postgresql 2>/dev/null
-brew install python 2>/dev/null
-brew install vim 2>/dev/null
+brew install ag
+brew install binutils
+brew install cloc
+brew install coreutils
+brew install exiftool
+brew install ffmpeg
+brew install git
+brew install git-lfs
+brew install git-when-merged
+brew install haskell-stack
+brew install jq
+brew install node
+brew install osquery
+brew install p7zip
+brew install parallel
+brew install postgresql
+brew install python
+brew install vim
 
 >&2 echo "----> Creating necessary directories..."
 mkdir -p ~/Desktop/code
 mkdir -p ~/Desktop/code/hack
+rm -rf ~/s
 mkdir -p ~/s
 mkdir -p ~/.stack
 
@@ -63,13 +64,13 @@ ln -sf ~/Desktop/config/dotfiles/stack ~/.stack/config.yaml
 stack setup
 git clone https://github.com/jaspervdj/stylish-haskell.git ~/Desktop/code/hack/stylish-haskell
 if [[ $? -ne 0 ]]; then
-  >&2 echo "----> Failed to download stylish-haskell."
+  >&2 echo "----> ERROR: Failed to download stylish-haskell."
   exit 5
 fi
 ( cd ~/Desktop/code/hack/stylish-haskell; stack install )
 
 >&2 echo "----> Creating shortcut symlinks..."
-ln -sf ~/Desktop ~/s/v
+ln -sf /Volumes ~/s/v
 ln -sf ~/Desktop ~/s/d
 ln -sf ~/Desktop/code ~/s/c
 ln -sf ~/Desktop/code/hack ~/s/h
@@ -111,7 +112,11 @@ bin/install_application virtualbox
 bin/install_application vlc
 
 >&2 echo "----> Installing Python programs..."
-pip install autopep8 2>/dev/null
+pip install autopep8
+if [[ $? -ne 0 ]]; then
+  >&2 echo "----> ERROR: Failed to install autopep8."
+  exit 6
+fi
 
 >&2 echo "----> Copying fonts..."
 rsync -avPz $DIR/../fonts/Input/* /Library/Fonts
