Supress debugging info

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -14,27 +14,32 @@ if [[ ! -d /Library/Developer/CommandLineTools ]]; then
 fi
 
 >&2 echo "----> Installing Homebrew..."
-ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+curl https://raw.githubusercontent.com/Homebrew/install/master/install >/tmp/install_homebrew.rb
+if [[ $? -ne 0 ]]; then
+  >&2 echo "----> Failed to download homebrew installer."
+  exit 4
+fi
+echo | ruby /tmp/install_homebrew.rb
 
 >&2 echo "----> Installing command-line programs with Homebrew..."
-brew install ag
-brew install binutils
-brew install cloc
-brew install coreutils
-brew install exiftool
-brew install ffmpeg
-brew install git
-brew install git-lfs
-brew install git-when-merged
-brew install haskell-stack
-brew install jq
-brew install node
-brew install osquery
-brew install p7zip
-brew install parallel
-brew install postgresql
-brew install python
-brew install vim
+brew install ag 2>/dev/null
+brew install binutils 2>/dev/null
+brew install cloc 2>/dev/null
+brew install coreutils 2>/dev/null
+brew install exiftool 2>/dev/null
+brew install ffmpeg 2>/dev/null
+brew install git 2>/dev/null
+brew install git-lfs 2>/dev/null
+brew install git-when-merged 2>/dev/null
+brew install haskell-stack 2>/dev/null
+brew install jq 2>/dev/null
+brew install node 2>/dev/null
+brew install osquery 2>/dev/null
+brew install p7zip 2>/dev/null
+brew install parallel 2>/dev/null
+brew install postgresql 2>/dev/null
+brew install python 2>/dev/null
+brew install vim 2>/dev/null
 
 >&2 echo "----> Creating necessary directories..."
 mkdir -p ~/Desktop/code
@@ -46,28 +51,32 @@ mkdir -p ~/.stack
 cp ~/Desktop/config/etc/DS_Store ~/.DS_Store
 
 >&2 echo "----> Creating symlinks..."
-ln -s ~/Desktop/config ~/.config
-ln -s ~/Desktop/config/dotfiles/ackrc ~/.ackrc
-ln -s ~/Desktop/config/dotfiles/editorconfig ~/.editorconfig
-ln -s ~/Desktop/config/dotfiles/gitconfig ~/.gitconfig
-ln -s ~/Desktop/config/dotfiles/gitignore ~/.gitignore
-ln -s ~/Desktop/config/dotfiles/vimrc ~/.vimrc
+ln -sf ~/Desktop/config ~/.config
+ln -sf ~/Desktop/config/dotfiles/ackrc ~/.ackrc
+ln -sf ~/Desktop/config/dotfiles/editorconfig ~/.editorconfig
+ln -sf ~/Desktop/config/dotfiles/gitconfig ~/.gitconfig
+ln -sf ~/Desktop/config/dotfiles/gitignore ~/.gitignore
+ln -sf ~/Desktop/config/dotfiles/vimrc ~/.vimrc
 
 >&2 echo "----> Setting stack up..."
-ln -s ~/Desktop/config/dotfiles/stack ~/.stack/config.yaml
+ln -sf ~/Desktop/config/dotfiles/stack ~/.stack/config.yaml
 stack setup
-git clone git@github.com:jaspervdj/stylish-haskell.git ~/Desktop/code/hack/stylish-haskell
+git clone https://github.com/jaspervdj/stylish-haskell.git ~/Desktop/code/hack/stylish-haskell
+if [[ $? -ne 0 ]]; then
+  >&2 echo "----> Failed to download stylish-haskell."
+  exit 5
+fi
 ( cd ~/Desktop/code/hack/stylish-haskell; stack install )
 
 >&2 echo "----> Creating shortcut symlinks..."
-ln -s ~/Desktop ~/s/v
-ln -s ~/Desktop ~/s/d
-ln -s ~/Desktop/code ~/s/c
-ln -s ~/Desktop/code/hack ~/s/h
-ln -s ~/Downloads ~/s/w
-ln -s ~/Movies ~/s/o
-ln -s ~/Dropbox/projects ~/s/p
-ln -s ~/Dropbox/print ~/s/r
+ln -sf ~/Desktop ~/s/v
+ln -sf ~/Desktop ~/s/d
+ln -sf ~/Desktop/code ~/s/c
+ln -sf ~/Desktop/code/hack ~/s/h
+ln -sf ~/Downloads ~/s/w
+ln -sf ~/Movies ~/s/o
+ln -sf ~/Dropbox/projects ~/s/p
+ln -sf ~/Dropbox/print ~/s/r
 
 >&2 echo "----> Including old versions of casks..."
 brew tap caskroom/versions
@@ -102,15 +111,10 @@ bin/install_application virtualbox
 bin/install_application vlc
 
 >&2 echo "----> Installing Python programs..."
-pip install autopep8
+pip install autopep8 2>/dev/null
 
 >&2 echo "----> Copying fonts..."
-rsync -avPz $DIR/../fonts/Input/* ~/Library/Fonts
-
->&2 echo "----> Setting startup items..."
-# TODO: Remove all existing startup items first?
-osascript -e 'tell application "System Events" to make login item at end with properties {path:"~/Applications/Spectacle.app", hidden:false}'
-osascript -e 'tell application "System Events" to make login item at end with properties {path:"~/Applications/Google Chrome.app", hidden:false}'
+rsync -avPz $DIR/../fonts/Input/* /Library/Fonts
 
 >&2 echo "----> Setting fish as the default shell..."
 chsh -s /usr/local/bin/fish
