Add polymer

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -123,6 +123,13 @@ if [[ $? -ne 0 ]]; then
   exit 6
 fi
 
+>&2 echo "----> Installing Node.js programs..."
+npm install -g polymer-cli
+if [[ $? -ne 0 ]]; then
+  >&2 echo "----> ERROR: Failed to install polymer-cli."
+  exit 7
+fi
+
 >&2 echo "----> Copying fonts..."
 rsync -avPz $DIR/../fonts/Input/* /Library/Fonts
 
