Check for stylish-haskell first

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -62,10 +62,12 @@ ln -sf ~/Desktop/config/dotfiles/vimrc ~/.vimrc
 >&2 echo "----> Setting stack up..."
 ln -sf ~/Desktop/config/dotfiles/stack ~/.stack/config.yaml
 stack setup
-git clone https://github.com/jaspervdj/stylish-haskell.git ~/Desktop/code/hack/stylish-haskell
-if [[ $? -ne 0 ]]; then
-  >&2 echo "----> ERROR: Failed to download stylish-haskell."
-  exit 5
+if [[ ! -d ~/Desktop/code/hack/stylish-haskell ]]; then
+  git clone https://github.com/jaspervdj/stylish-haskell.git ~/Desktop/code/hack/stylish-haskell
+  if [[ $? -ne 0 ]]; then
+    >&2 echo "----> ERROR: Failed to download stylish-haskell."
+    exit 5
+  fi
 fi
 ( cd ~/Desktop/code/hack/stylish-haskell; stack install )
 
